services:
  gno:
    image: ghcr.io/gnolang/gno/gnodev:master
    ports:
      - "8888:8888"
      - "26657:26657" 
    entrypoint: ["/usr/bin/gnodev", "local", "--add-account", "g1ldng3lt5mdmt92w2xphmjqu2r0pespsyfge66x=100000000000ugnot"]
    container_name: gno